---
- name: Supervisor Setup - Install supervisor
  pip: name=supervisor state=latest extra_args='--pre'
  tags:
    - supervisor-setup

- name: Supervisor Setup - Set up supervisor init script
  copy: src=supervisor/supervisord dest=/etc/init.d/supervisor
  tags:
    - supervisor-setup

- name: Supervisor Setup - Create supervisor conf directory
  file: path=/etc/supervisor/ state=directory
  tags:
    - supervisor-setup
    - supervisor-conf

- name: Supervisor Setup - Configure supervisord main config
  template: src=supervisor_setup/supervisord.conf.j2 dest=/etc/supervisor/supervisord.conf backup=yes
  tags:
    - supervisor-setup
    - supervisor-conf
