---
- name: create android sdk path
  file: path={{ android_sdk_path }} state=directory
  tags:
    - create-sdk-path

- name: Download android sdk
  shell: wget "{{ jenkins_android_sdk_link }}" -O {{ downloaded_android_sdk_path }}
  tags:
    - download-android-sdk

- name: Remove android sdk folder
  file: path={{ android_sdk_path }} state=absent
  tags:
    - remove-sdk-folder

- name: Extract android sdk tar file
  shell: tar xvf {{ downloaded_android_sdk_path }} -C /opt/
  tags:
    - extract-android-sdk

- name: Update Android sdk
  shell: chdir={{ android_sdk_path }}/tools echo "y" | ./android update sdk --no-ui
  tags:
    - update-android-sdk

- name: Update Android sdk - specific revision 
  shell: chdir={{ android_sdk_path }}/tools echo "y" | ./android update sdk --no-ui --filter {{ android_build_tools_revision_number }}
  tags:
    - update-android-sdk-revision
