- name: Add entry to 90-cloud-init-users
  lineinfile:
    dest: /etc/sudoers.d/90-cloud-init-users
    state: present
    line: jenkins ALL=(ALL) NOPASSWD:ALL
    validate: visudo -cf %s

- name: Create master key file path
  file: path={{ master_key_dir }} state=directory

- name: Copy the master key file
  template: src=master.j2 dest={{ master_key_dir }}/master

- name: Create dynamo dir as user jenkins
  file: path={{ dynamo_dir }} state=directory owner=jenkins

- name: Download and unzip dynamodb from s3
  unarchive:
    src: http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.zip
    dest: "{{ dynamo_dir }}"
    remote_src: yes
    copy: no
    owner: jenkins

- name: Copy run-local-dynamo shell script
  copy: 
    src: dynamo/run-local-dynamo.sh 
    dest: "{{ dynamo_dir }}" 
    mode: u+x
    owner: jenkins

- name: Run run-local-dynamo shell script
  shell: "{{ dynamo_dir }}/run-local-dynamo.sh"
  become: yes
  become_user: jenkins
