---
- name: Add jenkins user
  user: name={{ jenkins_user }} shell=/bin/bash
  tags:
    - add-jenkins-user

- name: Create jenkins lib directory
  file: path={{ jenkins_lib_dir }} state=directory owner={{ jenkins_user }} group={{ jenkins_user }}
  tags:
    - add-jenkins-lib-dir

- name: Create ssh directory
  file: path={{ jenkins_home_dir }}/.ssh state=directory owner={{ jenkins_user }} group={{ jenkins_user }} mode=0700
  tags:
    - create-jenkins-ssh-folder

- name: Copy jenkins master private key
  copy: content={{ jenkins_master_private_key }} dest={{ jenkins_home_dir }}/.ssh/id_rsa owner={{ jenkins_user }} group={{ jenkins_user }} mode=0400
  tags:
    - copy-private-key

- name: Create SSH Authorized File
  file: path={{ jenkins_home_dir }}/.ssh/{{ ssh_authorized_file }} state=touch owner={{ jenkins_user }} group={{ jenkins_user }} mode=0644
  tags:
    - create-authorized-file

- name: Copy jenkins master public key
  blockinfile: content={{ jenkins_master_public_key }} dest={{ jenkins_home_dir }}/.ssh/{{ ssh_authorized_file }} owner={{ jenkins_user }} group={{ jenkins_user }} mode=0644
  tags:
    - copy-public-key

- name: Add environment variables
  blockinfile: content={{ environment_configs }} dest={{ environment_file }}
  tags:
    - set-env-configs 

- name: Copy jenkins slave file
  copy: src=slave.jar dest={{ jenkins_home_dir }} owner={{ jenkins_user }} group={{ jenkins_user }}
  tags:
    - copy-jenkins-slave
