---
- name: Create temp folder to store json templates
  local_action: file path={{ tmp_aws_alerts }} state=directory
  tags:
      - setup-tmp-dir

- name: Get single ec2 remote facts
  local_action:
        ec2_remote_facts
        filters=private-ip-address={{ private_ip }}
        region={{ aws_region }}
        aws_access_key={{ EC2_AWS_ACCESS_KEY_ID }}
        aws_secret_key={{ EC2_AWS_SECRET_ACCESS_KEY }}
  register: ec2_facts
  tags:
    - gather-ec2-facts

- name: Generate alert json
  local_action: template src=templates/aws_downtime.j2 dest=/tmp/aws_alerts/{{ item.tags.Name }}_aws_downtime.json
  with_items:
    - "{{ ec2_facts.instances }}"
  tags:
    - generate-alert-template
 
- name: Configure aws alert
  local_action: shell aws cloudwatch put-metric-alarm --cli-input-json file:///{{ tmp_aws_alerts }}/{{ item.tags.Name }}_aws_downtime.json
  with_items:
    - "{{ ec2_facts.instances }}"
  tags:
    - configure-downtime-alert

- name: Remove temp folder used to store json templates
  local_action: file path={{ tmp_aws_alerts }} state=absent
  tags:
      - remove-tmp-dir
