---
- name: Install Latest MySQL Server
  apt: name=mysql-server state=latest
  register: mysql_install_result
  notify:
    - restart mysql
  ignore_errors: True
  tags:
    - mysql-server

- name: set up mysql - copy .my.cnf file with root password credentials
  template: src={{role_path}}/templates/mysql_setup/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  notify:
    - restart mysql
  tags:
    - mysql-server
    - mysql-server-setup
    - mysql-server-security-setup

- name: First time set mysql password
  mysql_user: name=root host=localhost password={{ root_db_password }} login_password="" login_user=root
  register: set_mysql_root_password
  ignore_errors: True
  tags:
    - mysql-server
    - mysql-server-setup
    - mysql-server-security-setup

- name: set up mysql - update mysql root password for all root accounts
  mysql_user: name=root host=localhost password={{ root_db_password }}
  when: set_mysql_root_password|failed
  tags:
    - mysql-server
    - mysql-server-setup
    - mysql-server-security-setup

- name: update bind address settings in mysql
  command: sed -i "s/bind-address.*/bind-address = {{mysql_bind_address}}/" /etc/mysql/my.cnf
  notify:
    - restart mysql
  tags:
    - mysql-server
    - mysql-server-setup

- name: set up mysql - update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ root_db_password }}
  with_items:
    - '{{ansible_hostname}}'
    - '{{inventory_hostname}}'
    - 127.0.0.1
    - ::1
  tags:
    - mysql-server
    - mysql-server-setup
    - mysql-server-security-setup

- name: set up mysql - ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - $inventory_hostname
  tags:
    - mysql-server
    - mysql-server-setup
    - mysql-server-security-setup
