---
- name: Install MySQL Dependencies
  apt: name={{item}} state=latest
  with_items:
    - libapache2-mod-auth-mysql
    - php5-mysql
  ignore_errors: True
  tags:
    - mysql-deps

- name: set up mysql - install python-mysqldb
  apt: name=python-mysqldb state=latest
  ignore_errors: True
  tags:
    - mysql-deps
