- name: Check if OS is CentOS
  fail: msg="IPA server should be CentOS"
  when: ansible_distribution != 'CentOS' 

- name: Update CentOS packages
  yum: name=* state=latest update_cache=yes

- name: Ensure EPEL installed
  yum: name=epel-release state=latest

- name: Install haveged
  yum: name=haveged state=present
  notify: restart haveged

- name: Set haveged as upstart
  service: name=haveged enabled=yes

- name: Set Hostname
  hostname: name={{ inventory_hostname }}
  when: inventory_hostname != ansible_hostname

- name: Ensure hostname in /etc/sysconfig/network
  lineinfile: dest=/etc/sysconfig/network regexp="^HOSTNAME" line="HOSTNAME={{ inventory_hostname }}" state=present

- name: Ensure hostname is in /etc/hosts
  lineinfile: dest=/etc/hosts regexp="^{{ ansible_default_ipv4.address }}.+$" line="{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ inventory_hostname_short }}" state=present

- name: Edit /etc/cloud/cloud.cfg to preserve hostname post reboot
  lineinfile: 'dest=/etc/cloud/cloud.cfg regexp="^preserve_hostname" line="preserve_hostname: true" state=present'

- name: Edit ifcfg-eth0 to preserve resolve.conf
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0 regexp="^PEERDNS" line='PEERDNS="no" ' state=present 

- name: Write swapfile
  command: dd if=/dev/zero of={{ swapfile_location }} bs=1M count={{ swapfile_size }} creates={{ swapfile_location }}
  register: write_swapfile
  when: swapfile_size != false

- name: Set swapfile permissions
  file: path={{ swapfile_location }} mode=600
  when: swapfile_size != false

- name: Create swapfile
  command: mkswap {{ swapfile_location }}
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/sbin:/usr/sbin:/sbin"
  register: create_swapfile
  when: swapfile_size != false and write_swapfile.changed

- name: Enable swapfile
  command: swapon {{ swapfile_location }}
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/sbin:/usr/sbin:/sbin"
  when: swapfile_size != false and create_swapfile.changed

- name: Add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="{{ swapfile_location }}   none    swap    sw    0   0" state=present
  when: swapfile_size != false

- name: Copy /etc/environment file
  template: src=etc-environment.j2 dest=/etc/environment owner=root mode=0644

- name: Install ipa-server packages
  yum: name={{ item }} state=present
  with_items:
  - ipa-server
  - bind
  - bind-dyndb-ldap
  - bind-utils
  - ipa-server-dns
