ipa_usr:
  - username: "achokshi"
    email: "anand@tala.co"
    fname: "Anand"
    lname: "Chokshi"
    ssh: "yes"
    sudo: "yes"
    group:
      - "ug-dev-all"
      - "ug-qa-all"
      - "ug-prod-all"
    a_group: "tala-readonly"
    rds_privs:
      - rds_instance: "{{ rds_servers['us-west-2-dev-rds1'] }}"
        privs:
          - "%.*:ALL"
      - rds_instance: "{{ rds_servers['ap-southeast-1-dev-rds1'] }}"
        privs:
          - "%.*:ALL"
      - rds_instance: "{{ rds_servers['eu-west-1-dev-rds1'] }}"
        privs:
          - "%.*:ALL"
      - rds_instance: "{{ rds_servers['us-west-2-prd-rds2'] }}"
        privs:
          - "anand_temp.*:ALL"
          - "experiments.*:ALL"
          - "profiling.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "datateam.*:SELECT"
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-prd-rds1'] }}"
        privs:
          - "anand_temp.*:ALL"
          - "experiments.*:ALL"
          - "profiling.*:ALL"
          - "datateam.*:SELECT"
          - "loans.*:SELECT"
          - "loans._trap_log:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-prd-rds1'] }}"
        privs:
          - "anand_temp.*:ALL"
          - "experiments.*:ALL"
          - "profiling.*:ALL"
          - "datateam.*:SELECT"
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-prd-rds1'] }}"
        privs:
          - "anand_temp.*:ALL"
          - "experiments.*:ALL"
          - "profiling.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "datateam.*:SELECT"
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-prd-rds2'] }}"
        privs:
          - "anand_temp.*:ALL"
          - "experiments.*:ALL"
          - "profiling.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "datateam.*:SELECT"
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['us-west-2-prd-rds1'] }}"
        privs:
          - "anand_temp.*:ALL"
          - "experiments.*:ALL"
          - "profiling.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "datateam.*:SELECT"
          - "loans.*:SELECT"
