ipa_usr:
  - username: "pong"
    email: "pong@tala.co"
    fname: "Peter"
    lname: "Ong"
    ssh: "yes"
    sudo: "yes"
    group:
      - "ug-prod-all"
      - "ug-dev-all"
      - "ug-stag-all"
      - "ug-qa-all"
      - "ug-ipa-all"
    aws_group: "tala-fullaccess"
    rds_privs:
      - rds_instance: "{{ rds_servers['us-west-2-dev-rds1'] }}"
        privs:
          - "*.*:PROCESS"
          - "loans_dev.*:ALL"
          - "loans_qa2.*:ALL"
          - "loans_qa.*:ALL"
          - "loans_services.*:ALL"
          - "loans_staging.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "mysql.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-dev-rds1'] }}"
        privs:
          - "*.*:PROCESS"
          - "loans_dev.*:ALL"
          - "loans_qa2.*:ALL"
          - "loans_qa.*:ALL"
          - "loans_services.*:ALL"
          - "loans_staging.*:ALL"
          - "loans.*:SELECT"
          - "mysql.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-dev-rds1'] }}"
        privs:
          - "*.*:PROCESS"
          - "loans_dev.*:ALL"
          - "loans_qa2.*:ALL"
          - "loans_qa.*:ALL"
          - "loans_services.*:ALL"
          - "loans_staging.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "mysql.*:SELECT"
      - rds_instance: "{{ rds_servers['us-west-2-prd-rds2'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "mysql.*:SELECT"
          - "payments.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-prd-rds1'] }}"
        privs:
          - "loans.*:SELECT"
          - "mysql.*:SELECT"
          - "payments.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-prd-rds1'] }}"
        privs:
          - "loans.*:SELECT"
          - "mysql.*:SELECT"
          - "payments.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-prd-rds1'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "mysql.*:SELECT"
          - "payments.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-prd-rds2'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "mysql.*:SELECT"
          - "payments.*:SELECT"
      - rds_instance: "{{ rds_servers['us-west-2-prd-rds1'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "mysql.*:SELECT"
          - "payments.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-dev-rds1'] }}"
        privs:
          - "*.*:PROCESS"
          - "loans_dev.*:ALL"
          - "loans_qa2.*:ALL"
          - "loans_qa.*:ALL"
          - "loans_services.*:ALL"
          - "loans_staging.*:ALL"
          - "loans.*:SELECT"
          - "mysql.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-dev-rds1'] }}"
        privs:
          - "*.*:PROCESS"
          - "loans_dev.*:ALL"
          - "loans_qa2.*:ALL"
          - "loans_qa.*:ALL"
          - "loans_services.*:ALL"
          - "loans_staging.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "mysql.*:SELECT"
