ipa_usr:
  - username: "qtran"
    email: "quang@tala.co"
    fname: "Quang"
    lname: "Tran"
    ssh: "yes"
    group:
      - "ug-product-all"
    rds_privs:
      - rds_instance: "{{ rds_servers['us-west-2-dev-rds1'] }}"
        privs:
          - "*.*:USAGE"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans_demo.*:SELECT"
          - "loans_dev.*:SELECT"
          - "loans_qa2.*:SELECT"
          - "loans_qa.*:SELECT"
          - "loans_staging.*:SELECT"
          - "loans.*:SELECT"
          - "payments.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-dev-rds1'] }}"
        privs:
          - "*.*:USAGE"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans_demo.*:SELECT"
          - "loans_dev.*:SELECT"
          - "loans_qa2.*:SELECT"
          - "loans_qa.*:SELECT"
          - "loans_staging.*:SELECT"
          - "loans.*:SELECT"
          - "payments.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-dev-rds1'] }}"
        privs:
          - "*.*:USAGE"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans_demo.*:SELECT"
          - "loans_dev.*:SELECT"
          - "loans_qa2.*:SELECT"
          - "loans_qa.*:SELECT"
          - "loans_staging.*:SELECT"
          - "loans.*:SELECT"
          - "payments.*:SELECT"
      - rds_instance: "{{ rds_servers['us-west-2-prd-rds2'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans.*:SELECT"
          - "payments.*:SELECT"
          - "profiling.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-prd-rds1'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans.*:SELECT"
          - "payments.*:SELECT"
          - "profiling.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-prd-rds1'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans.*:SELECT"
          - "payments.*:SELECT"
          - "profiling.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-prd-rds1'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans.*:SELECT"
          - "payments.*:SELECT"
          - "profiling.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-prd-rds2'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans.*:SELECT"
          - "payments.*:SELECT"
          - "profiling.*:SELECT"
      - rds_instance: "{{ rds_servers['us-west-2-prd-rds1'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans.*:SELECT"
          - "payments.*:SELECT"
          - "profiling.*:SELECT"
