---
- name: restart new relic
  service:
    name: newrelic-sysmond
    state: restarted

- name: run new relic installer
  shell: NR_INSTALL_SILENT=true newrelic-install install
  notify:
    - restart

