ipa_usr:
  - username: "asommerlatt"
    email: "amy@tala.co"
    fname: "Amy"
    lname: "Sommerlatt"
    ssh: "yes"
    group:
      - "ug-expansion-all"
    rds_privs:
      - rds_instance: "{{ rds_servers['us-west-2-prd-rds2'] }}"
        privs:
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-prd-rds1'] }}"
        privs:
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-prd-rds1'] }}"
        privs:
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-prd-rds1'] }}"
        privs:
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-prd-rds2'] }}"
        privs:
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['us-west-2-prd-rds1'] }}"
        privs:
          - "loans.*:SELECT"
