ipa_usr:
  - username: "fmuya"
    email: "fred@tala.co"
    fname: "Fred"
    lname: "Muya"
    ssh: "yes"
    sudo: "yes"
    group:
      - "ug-prod-all"
      - "ug-dev-all"
      - "ug-qa-all"
      - "ug-stag-all"
      - "ug-ipa-all"
    aws_group: "tala-fullaccess"
    rds_privs:
      - rds_instance: "{{ rds_servers['us-west-2-dev-rds1'] }}"
        privs:
          - "*.*:SELECT"
          - "inventure_services_dev.*:ALL"
          - "inventure_services.*:ALL"
          - "loans_dev.*:ALL"
          - "loans_qa2.*:ALL"
          - "loans_qa.*:ALL"
          - "loans_staging.*:ALL"
          - "payments_dev.*:ALL"
          - "payments.*:ALL"
          - "profiles.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans_bd.*:SELECT"
          - "loans_ng.*:SELECT"
          - "loans_ug.*:SELECT"
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-dev-rds1'] }}"
        privs:
          - "*.*:SELECT"
          - "inventure_services_dev.*:ALL"
          - "inventure_services.*:ALL"
          - "loans_dev.*:ALL"
          - "loans_qa2.*:ALL"
          - "loans_qa.*:ALL"
          - "loans_staging.*:ALL"
          - "payments_dev.*:ALL"
          - "payments.*:ALL"
          - "profiles.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans_bd.*:SELECT"
          - "loans_ng.*:SELECT"
          - "loans_ug.*:SELECT"
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-dev-rds1'] }}"
        privs:
          - "*.*:SELECT"
          - "inventure_services_dev.*:ALL"
          - "inventure_services.*:ALL"
          - "loans_dev.*:ALL"
          - "loans_qa2.*:ALL"
          - "loans_qa.*:ALL"
          - "loans_staging.*:ALL"
          - "payments_dev.*:ALL"
          - "payments.*:ALL"
          - "profiles.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans_bd.*:SELECT"
          - "loans_ng.*:SELECT"
          - "loans_ug.*:SELECT"
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['us-west-2-prd-rds2'] }}"
        privs:
          - "inventure_services_dev.*:ALL"
          - "inventure_services.*:ALL"
          - "payments_dev.*:ALL"
          - "payments.*:ALL"
          - "profiles.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans.*:SELECT"
#          - "profiles.businesses:UPDATE"
      - rds_instance: "{{ rds_servers['ap-southeast-1-prd-rds1'] }}"
        privs:
          - "inventure_services_dev.*:ALL"
          - "inventure_services.*:ALL"
          - "payments_dev.*:ALL"
          - "payments.*:ALL"
          - "profiles.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans.*:SELECT"
          - "profiles.businesses:UPDATE"
      - rds_instance: "{{ rds_servers['ap-southeast-1-prd-rds1'] }}"
        privs:
          - "inventure_services_dev.*:ALL"
          - "inventure_services.*:ALL"
          - "payments_dev.*:ALL"
          - "payments.*:ALL"
          - "profiles.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans.*:SELECT"
#          - "profiles.businesses:UPDATE"
      - rds_instance: "{{ rds_servers['eu-west-1-prd-rds1'] }}"
        privs:
          - "inventure_services_dev.*:ALL"
          - "inventure_services.*:ALL"
          - "payments_dev.*:ALL"
          - "payments.*:ALL"
          - "profiles.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans.*:SELECT"
#          - "profiles.businesses:UPDATE"
      - rds_instance: "{{ rds_servers['eu-west-1-prd-rds2'] }}"
        privs:
          - "inventure_services_dev.*:ALL"
          - "inventure_services.*:ALL"
          - "payments_dev.*:ALL"
          - "payments.*:ALL"
          - "profiles.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans.*:SELECT"
#          - "profiles.businesses:UPDATE"
      - rds_instance: "{{ rds_servers['us-west-2-prd-rds1'] }}"
        privs:
          - "inventure_services_dev.*:ALL"
          - "inventure_services.*:ALL"
          - "payments_dev.*:ALL"
          - "payments.*:ALL"
          - "profiles.*:ALL"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "invre.*:SELECT"
          - "loans.*:SELECT"
#          - "profiles.businesses:UPDATE"
