ipa_usr:
  - username: "pmbalo"
    email: "pamela@tala.co"
    fname: "Pamela"
    lname: "Mbalo"
    ssh: "yes"
    group:
      - "ug-finance-analytics-all"
    rds_privs:
      - rds_instance: "{{ rds_servers['us-west-2-dev-rds1'] }}"
        privs:
          - "*.*:USAGE"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-dev-rds1'] }}"
        privs:
          - "*.*:USAGE"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-dev-rds1'] }}"
        privs:
          - "*.*:USAGE"
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
      - rds_instance: "{{ rds_servers['us-west-2-prd-rds2'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "profiling.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-prd-rds1'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "profiling.*:SELECT"
      - rds_instance: "{{ rds_servers['ap-southeast-1-prd-rds1'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "profiling.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-prd-rds1'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "profiling.*:SELECT"
      - rds_instance: "{{ rds_servers['eu-west-1-prd-rds2'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "profiling.*:SELECT"
      - rds_instance: "{{ rds_servers['us-west-2-prd-rds1'] }}"
        privs:
          - "PROCEDURE mysql.change_time_zone:EXECUTE"
          - "loans.*:SELECT"
          - "profiling.*:SELECT"
