---
- name: create monitor scripts directory
  file: path={{ monitor_scripts_dir }} state=directory
  tags:
   - create-monitor-dir

- name: install monit service
  apt: name=monit state=present update_cache=yes
  tags:
    - install-monit

- name: copy monit custom config
  template: src={{ item }} dest={{ monitor_scripts_dir }}
  with_items:
    - non-prod-monit
    - shared_functions.sh
    - slackAlert.sh
  tags:
    - configure-monit

- name: copy custom monitrc file
  template: src=monit-web dest={{ monit_custom_config_path }}/monit-web
  tags:
    - configure-monit

- name: make monitor script executable
  file: path={{ monitor_scripts_dir }}{{ monit_alert_script }}.sh mode="0755"
  notify:
    - restart-monit
  tags:
    - configure-monit
