---
- name: set timestamp
  set_fact: timestamp={{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}

- name: Check that the application directory is available
  stat: path={{whatsapp_app_application_dir}}
  register: p

- name: Application path exists and is a directory
  debug: msg="Application path is ok!"
  when: p.stat.isdir is defined and p.stat.isdir

- name: Application path does not exists
  fail: msg="Application path does not exists or is not directory"
  when: p.stat.isdir is not defined or not p.stat.isdir

- name: Create users groups for the whatsapp applications
  group: name={{whatsapp_app_sys_user_group}} state=present

- name: Create users for whatsapp applications
  user: name={{whatsapp_app_sys_user_name}} groups="{{whatsapp_app_sys_user_group}},www-data" append=yes

- name: Make sure config dir exists
  file: path={{inventure_config_path}} state=directory
  tags:
    - base-config

- name: Install memcached
  apt: name=memcached
  tags:
    - memcached

- name: Install python memcached
  apt: name=python-memcache
  tags:
    - memcached #python-dev libffi-dev libssl-dev

- name: Install Python libraries required
  apt: name={{item}}
  with_items:
    - python-dev
    - libffi-dev
    - libssl-dev
  tags:
    - python-ssl

- name: Set up Config file
  template: src=base_config.json.j2 dest={{inventure_config_path}}/{{whatsapp_app_config_file}} owner={{whatsapp_app_sys_user_name}}
  tags:
    - base-config

- name: Make sure zendesk sync config dir exists
  file: path={{inventure_config_path}} state=directory
  tags:
    - zd-sync

- name: Set up Zendesk Sync Config file
  template: src=zendesk-sync-config.json.j2 dest={{inventure_config_path}}/{{zd_sync_conf_file}} owner={{whatsapp_app_sys_user_name}}
  tags:
    - zd-sync
    - zd-sync-config

- name: Create zendesk sync app application log path
  file: path={{zd_sync_app_base_log_path}} state=directory
  tags:
    - zd-sync

- name: Check/create zendesk sync application log files
  file: path={{zd_sync_app_base_log_path}}{{zd_sync_base_log_file_name}} owner={{whatsapp_app_sys_user_name}} group={{whatsapp_app_sys_user_group}} state=touch
  tags:
    - zd-sync

- name: Create zendesk sync application debug files
  file: path={{zd_sync_app_base_log_path}}/{{zd_sync_debug_file_name}} owner={{whatsapp_app_sys_user_name}} group={{whatsapp_app_sys_user_group}} state=touch
  tags:
    - zd-sync

- name: Create whatsapp app application log path
  file: path={{whatsapp_app_base_log_path}} state=directory

- name: Check/create application log files
  file: path={{whatsapp_app_base_log_path}}{{whatsapp_app_base_log_file_name}} owner={{whatsapp_app_sys_user_name}} group={{whatsapp_app_sys_user_group}} state=touch

- name: Create application debug files
  file: path={{whatsapp_app_base_log_path}}/{{whatsapp_app_debug_file_name}} owner={{whatsapp_app_sys_user_name}} group={{whatsapp_app_sys_user_group}} state=touch

- name: Set up logrotate
  template: src=whatsapp-app-logrotate.j2 dest={{whatsapp_app_logrotate_file}}
  tags:
    - log-rotate

- name: Copy log files organizer
  copy: src={{ item.from }} dest={{ item.to }} mode=uog+x
  with_items:
    - { from: 'organize-logs.sh', to: '{{ whatsapp_app_base_log_path }}' }
    - { from: 'organize-logs.sh', to: '{{ zd_sync_app_base_log_path }}' }
    - { from: 'organize-logs.sh', to: '{{ incoming_messages_app_base_log_path }}' }
  tags:
    - organize-logs

- name: Set up logrotate for Zendesk Sync
  template: src=zd-sync-app-logrotate.j2 dest={{sync_zd_app_logrotate_file}}
  tags:
    - log-rotate
    - zd-sync

- name: Set up virtual env
  pip: virtualenv={{whatsapp_app_application_dir}}/whatsapp/{{whatsapp_app_virtual_env}} requirements={{whatsapp_app_application_dir}}/requirements.txt
  tags:
    - pip-install

- name: Flask application - Create webroot directory
  file: path={{whatsapp_app_webroot_path}} state=directory

- name: Flask application - Create symlink to application
  file: path={{whatsapp_app_webroot_path}}/whatsapp_api src={{whatsapp_app_application_dir}}/whatsapp state=link

- name: Flask application - Configure virtual host
  template: src=whatsapp_vhost.conf.j2 dest={{whatsapp_app_vhost}} owner={{whatsapp_app_sys_user_name}}
  tags:
    - conf-vhost

- name: Flask application - Create wsgi file
  template: src=whatsapp_api.wsgi.j2 dest={{whatsapp_app_vhost_wsgi_file}} owner={{whatsapp_app_sys_user_name}}

- name: Flask application - Enable vhost
  command: a2ensite {{whatsapp_app_api_name}}.conf
  # notify:
  #   - restart apache

- name: Flask application - Create sqlite db directory
  file: path={{whatsapp_app_db_dir_path}} state=directory owner={{whatsapp_app_apache_user}} group={{whatsapp_app_apache_group}}

- name: Check if sqlite db already exists
  stat: path={{whatsapp_app_db_dir_path}}{{whatsapp_app_db_file_name}}
  register: sqlite_db

- name: Back up existing sqlite db
  command: mv {{whatsapp_app_db_dir_path}}{{whatsapp_app_db_file_name}} '{{whatsapp_app_db_dir_path}}{{whatsapp_app_db_file_name}}.backup_{{timestamp}}'
  when: sqlite_db.stat.exists

- name: Flask application - Init sqlite db
  shell: sqlite3 {{whatsapp_app_db_dir_path}}{{whatsapp_app_db_file_name}} < {{whatsapp_app_db_schema}}

- name: Flask application - Change ownership of sqlite db
  file: path={{whatsapp_app_db_dir_path}}{{whatsapp_app_db_file_name}} owner={{whatsapp_app_apache_user}} mode=ug+rw group={{whatsapp_app_apache_group}} state=touch

- name: WhatsApp process - Create lock file directory
  file: path={{whatsapp_app_proc_lock_dir}} state=directory
  tags:
    - whatsapp-proc

- name: WhatsApp process - Make environment activation script executable
  file: path={{whatsapp_app_application_dir}}/.env state=file mode=a+x
  tags:
    - whatsapp-proc
    - im-proc

- name: Create incoming messages process application log path
  file: path={{incoming_messages_app_base_log_path}} state=directory
  tags:
    - im-proc

- name: WhatsApp process - Copy process manipulation script to init.d
  template: src=iv_whatsapp_proc.sh.j2 dest={{whatsapp_app_init_d_file}} mode=u+x
  tags:
    - whatsapp-proc

- name: Incoming Messages process - Create lock file directory
  file: path={{incoming_messages_proc_app_proc_lock_dir}} state=directory
  tags:
    - im-proc

- name: Incoming Messages process - Copy process manipulation script to init.d
  template: src=im_proc.sh.j2 dest={{incoming_messages_init_d_file}} mode=u+x
  tags:
    - im-proc

- name: Sync zendesk last message status - Create lock file directory
  file: path={{sync_zd_last_msg_status_proc_app_lock_dir}} state=directory
  tags:
    - zd-sync

- name: Sync zendesk last message status - Copy process manipulation script to init.d
  template: src=sync_last_msg_status.sh.j2 dest={{sync_zd_last_msg_status_init_d_file}} mode=u+x
  tags:
    - zd-sync

