---
- name: Set up Zendesk Sync Config file
  template: src=zendesk-sync-config.json.j2 dest={{inventure_config_path}}/{{zd_sync_conf_file}} owner={{whatsapp_app_sys_user_name}}
  tags:
    - zd-sync
    - zd-sync-config

- name: Create zendesk sync app application log path
  file: path={{zd_sync_app_base_log_path}} state=directory
  tags:
    - zd-sync

- name: Check/create zendesk sync application log files
  file: path={{zd_sync_app_base_log_path}}{{item}} owner={{whatsapp_app_sys_user_name}} group={{whatsapp_app_sys_user_group}} state=touch mode=ugo+rw
  with_items:
    - '{{zd_sync_base_log_file_name}}'
    - '{{zd_sync_debug_file_name}}'
    - '{{zd_sync_base_log_file_name_tr}}'
    - '{{zd_sync_debug_file_name_tr}}'
  tags:
    - zd-sync
    - zd-sync-log-permissions

- name: Set up logrotate for Zendesk Sync
  template: src=zd-sync-app-logrotate.j2 dest={{sync_zd_app_logrotate_file}}
  tags:
    - log-rotate
    - zd-sync

- name: Sync zendesk last message status - Create lock file directory
  file: path={{sync_zd_last_msg_status_proc_app_lock_dir}} state=directory
  tags:
    - zd-sync

- name: Sync zendesk last message status - Copy process manipulation script to init.d
  template: src=sync_last_msg_status.sh.j2 dest={{sync_zd_last_msg_status_init_d_file}} mode=u+x
  tags:
    - zd-sync

- name: Zendesk Sync App Flask application - Create webroot directory
  file: path={{zd_sync_app_webroot_path}} state=directory
  tags:
    - zd-sync
    - zd-sync-web-app

- name: Zendesk Sync App Flask application - Create symlink to application
  file: path={{zd_sync_app_webroot_path}}/zd_sync src={{whatsapp_app_application_dir}}/zendesk_sync state=link
  tags:
    - zd-sync
    - zd-sync-web-app

- name: Zendesk Sync App Flask application - Configure virtual host
  template: src=zd-sync-app/zd_sync_app_vhost.conf.j2 dest={{zd_sync_app_vhost}} owner={{whatsapp_app_sys_user_name}}
  tags:
    - zd-sync
    - zd-sync-web-app

- name: Zendesk Sync App Flask application - Create wsgi file
  template: src=zd-sync-app/zd_sync_api.wsgi.j2 dest={{zd_sync_app_vhost_wsgi_file}} owner={{whatsapp_app_sys_user_name}}
  tags:
    - zd-sync
    - zd-sync-web-app

- name: Zendesk Sync App Flask application - Enable vhost
  command: a2ensite {{zd_sync_api_name}}.conf
  # notify:
  #   - restart apache
  tags:
    - zd-sync
    - zd-sync-web-app

- name: Zendesk Sync App process - Copy Telerivet Sync process manipulation script to init.d
  template: src=zd-sync-app/zd_telerivet_sync.sh.j2 dest={{sync_zd_telerivet_init_d_file}} mode=u+x
  tags:
    - zd-sync
    - zd-telerivet-sync-proc
