---
- hosts: all
  become: yes
  become_user: root
  remote_user: ubuntu
  gather_facts: True
  roles:
       - {role: server-setup, tags: ['env-setup','package-update','python-setup','ssh-setup','utils-setup']}