---
- name: Create destination folder
  local_action: file path={{ aws_terraform_dir_path }}/{{ aws_service }} state=directory
  tags:
    - setup-paths

- name: generate terraform config file from template
  local_action: template src={{ aws_service }}_deploy.tf.j2 dest={{ aws_terraform_dir_path }}/{{ aws_service }}/deploy.tf
  tags:
    - generate-configs

- name: terraform plan
  local_action: shell terraform plan  chdir={{ aws_terraform_dir_path }}/{{ aws_service }}/
  environment:
     AWS_ACCESS_KEY_ID: "{{ aws_terraform_access_key }}"
     AWS_SECRET_ACCESS_KEY: "{{ aws_terraform_secret_key }}"
     AWS_DEFAULT_REGION: "{{ aws_region }}"
  no_log: no
  tags:
    - terraform-plan

- name: terraform plan
  local_action: shell terraform plan chdir={{ aws_terraform_dir_path }}/{{ aws_service }}/
  environment:
     AWS_ACCESS_KEY_ID: "{{ aws_terraform_access_key }}"
     AWS_SECRET_ACCESS_KEY: "{{ aws_terraform_secret_key }}"
     AWS_DEFAULT_REGION: "{{ aws_region }}"
  no_log: no
  tags:
    - terraform-apply

- name: Backup terraform state to s3 bucket
  local_action: shell terraform remote config -backend=s3 -backend-config="bucket={{ country_code }}-terraform-state-backup" -backend-config="key={ aws_terraform_dir_path }}/{{ aws_service }}/terraform.tfstate" -backend-config="region={{ aws_region }}"
  environment:
     AWS_ACCESS_KEY_ID: "{{ aws_terraform_access_key }}"
     AWS_SECRET_ACCESS_KEY: "{{ aws_terraform_secret_key }}"
     AWS_DEFAULT_REGION: "{{ aws_region }}"
  no_log: no
  tags:
    - terraform-backup
