- hosts: us-west-2-ipa01.tala.aws
  become: yes
  vars_prompt:
    - name: "username"
      prompt: "Username"
      private: no
  pre_tasks:
    - command: "echo {{ username }}"
      register: userecho
      failed_when: userecho.rc == 2
      changed_when: "userecho.rc != 0"
  roles:
    - { role: ipaschema, task_to_do: "delete_user" , inp_user: "{{ username }}" }

- hosts: openvpn
  become: yes
  roles:
    - { role: ovpn, task_to_do: "delete_user" , inp_user: "{{ hostvars['us-west-2-ipa01.tala.aws']['userecho']['stdout'] }}" }

